ttr: Scala関係のコードをリファクタリング

diff --git a/src/ttr-bootstrap b/src/ttr-bootstrap
--- a/src/ttr-bootstrap
+++ b/src/ttr-bootstrap
@@ -22,10 +22,10 @@ trap ":" 2 3 15
 ################################################################################
 # ttr.pl
 mkdir -p $HOME/.ttr
-if [ -e $HOME/.ttr/file-8ab60e6bb8cb8a6bcf8d4469ece7ecf4 ]; then
-    touch $HOME/.ttr/file-8ab60e6bb8cb8a6bcf8d4469ece7ecf4
+if [ -e $HOME/.ttr/file-298d9cd48dfc7bc003d0048b1642de6a ]; then
+    touch $HOME/.ttr/file-298d9cd48dfc7bc003d0048b1642de6a
 else
-cat <<\EOF_8ab60e6bb8cb8a6bcf8d4469ece7ecf4 > $HOME/.ttr/file-8ab60e6bb8cb8a6bcf8d4469ece7ecf4
+cat <<\EOF_298d9cd48dfc7bc003d0048b1642de6a > $HOME/.ttr/file-298d9cd48dfc7bc003d0048b1642de6a
 use strict;
 use warnings;
 use utf8;
@@ -537,24 +537,7 @@ sub process_macro_scala_sub {
         $output_fname = "scala-jar-$src_hash.jar";
     }
     my $jar_path = "$HOME/.ttr/$output_fname";
-    unless ( -e $jar_path) {
-
-        if (-e "$working_dir/classes") {
-            rmtree("$working_dir/classes");
-        }
-        mkdir("$working_dir/classes");
-
-        my $fork_code = ":";
-        if ($with_runtime) {
-            die "SCALA_HOME Not found" unless ($ENV{'SCALA_HOME'});
-            $fork_code = "$fork_code; (cd $working_dir/classes; jar -xf $ENV{SCALA_HOME}/lib/scala-library.jar) || exit 1"
-        }
-
-        fork_and_wait("$fork_code; scalac -d $working_dir/classes $src_path && jar -cf $jar_path -C $working_dir/classes .");
-
-        rmtree("$working_dir/classes");
-
-    }
+    process_macro_scala_compile($jar_path, $src_path, $with_runtime) unless ( -e $jar_path);
 
     my $hash = get_file_hash($jar_path);
     $global_attached_files = [@$global_attached_files,
@@ -564,6 +547,25 @@ sub process_macro_scala_sub {
          'for_subttr' => $for_subttr}];
     [{'name' => $jar_fname,
       'output_fname' => $output_fname}];
+}
+
+sub process_macro_scala_compile {
+    my ($jar_path, $src_path, $with_runtime) = @_;
+
+    if (-e "$working_dir/classes") {
+        rmtree("$working_dir/classes");
+    }
+    mkdir("$working_dir/classes");
+
+    my $fork_code = ":";
+    if ($with_runtime) {
+        die "SCALA_HOME Not found" unless ($ENV{'SCALA_HOME'});
+        $fork_code = "$fork_code; (cd $working_dir/classes; jar -xf $ENV{SCALA_HOME}/lib/scala-library.jar) || exit 1"
+    }
+
+    fork_and_wait("$fork_code; scalac -d $working_dir/classes $src_path && jar -cf $jar_path -C $working_dir/classes .");
+
+    rmtree("$working_dir/classes");
 }
 
 sub wrap_scala_class_lines {
@@ -911,9 +913,9 @@ if ($build_flag) {
     fork_and_wait("sh", $script_path, @script_args);
 }
 
-EOF_8ab60e6bb8cb8a6bcf8d4469ece7ecf4
+EOF_298d9cd48dfc7bc003d0048b1642de6a
 fi
-ln -f -s $HOME/.ttr/file-8ab60e6bb8cb8a6bcf8d4469ece7ecf4 $WORKING_DIR/ttr.pl
+ln -f -s $HOME/.ttr/file-298d9cd48dfc7bc003d0048b1642de6a $WORKING_DIR/ttr.pl
 
 ################################################################################
 # 
